### PR TITLE
[BUGFIX] Let f:cycle use "as" argument as scope of cycled variable

### PR DESCRIPTION
**Pull request by NamelessCoder**
This change allows f:cycle to be nested (see linked issue) - to work with multiple cycled variables in the same loop. In essence it identifies the instance of "values" using the value of the "as" argument and uses ViewHelperVariableContainer for storing the index.

Also changes the ViewHelper to not store the values but rather just store the index and read out the appropriate value based on that, from the provided values in arguments.

References: #5

### CODE REVIEW

**Comment by NamelessCoder** [comment]
I think this can be abandoned (underlying issue of reusing instances is solved). @bwaidelich and @mneuhaus your two cents please? If both agree, last one of you can just go ahead and close it.

**Comment by mneuhaus** [comment]
fine with me i guess :)

**Comment by mneuhaus** [comment]
@bwaidelich could you post your 2 cents about this? we have a "related" issue which would break the old behavior of the cycle viewHelper because of a Bug we need to fix, which the cycle kinda depends on to work. see discussion in https://github.com/TYPO3Fluid/Fluid/pull/77#issuecomment-195309441

**Comment by NamelessCoder** [comment]
Issue in #77 appears to be resolved - which means once again, this pull request should probably be abandoned. I still lean towards not reusing instances (this recent issue is just an example of the complication it adds) but it is in no way urgent and there are probably plenty other (better) ways to solve this particular `f:cycle` issue.

**Comment by bwaidelich** [comment]
Hi guys,

sorry for the lack of feedback, this one escaped me.

But sure, if #77 is resolved and the following template code
```
<f:for each="{0: 'a', 1: 'b', 2: 'c'}" as="x">
    <f:cycle values="{0: 'foo', 1: 'bar', 2: 'baz'}" as="cycle">{cycle}</f:cycle>
    <f:for each="{0: 'a', 1: 'b', 2: 'c'}" as="x2">
      <f:cycle values="{0: 'subfoo', 1: 'subbar', 2: 'subbaz'}" as="cycle">{cycle}</f:cycle>
    </f:for>
    <f:cycle values="{0: 'foo2', 1: 'bar2'}" as="cycle">{cycle}</f:cycle>
</f:for>
```

renders as

```
    foo
      subfoo
      subbar
      subbaz
    foo2

    bar
      subfoo
      subbar
      subbaz
    bar2

    baz
      subfoo
      subbar
      subbaz
    foo2
```

then please abandon this.
(Unfortunately I can't test this myself right now because I didn't get the latest version running with Flow yet).


PS: Every ViewHelper that adds something to the `ViewHelperVariableContainer` should *always* remove it again in order to prevent side-effects. That's not done in this change

**Comment by mneuhaus** [comment]
i just confirmed, that in the current version of Fluid Standalone the example of @bwaidelich renders as: 

```
foo
	subfoo
	subbar
	subbaz
foo2
bar
	subfoo
	subbar		
	subbaz
bar2

baz
	subfoo
	subbar
	subbaz
foo2
```

so i'm closing this :)

**Pull request closed without merging**
