### PR TITLE
[BUGFIX] Do not register Namespaces inside CDATA

### LINKED ISSUE #8: Throw exception for unresolved namespaces
Unknown namespaces used to be ignored in Fluid. But that lead to serious issues, e.g. when extracting template code into a partial while forgetting the namespace imports.
S.th. like
```html
<media:image image="{image}" />
```
Would try to render '{image}` directly if the `media:image` ViewHelper was ignored, leading to various errors that are very hard to debug.

With Flow 3.0 we therefore introduced a stricter handling of unknown namespaces, see: https://jira.neos.io/browse/FLOW-150

```html
<unknownNamespace:foo />
```

## Expected output

```
Error while rendering a ViewHelper
The namespace of ViewHelper notation "<unknownNamespace:foo.../>" could not be resolved.

Possible reasons are:
* you have a spelling error in the viewHelper namespace
* you forgot to import the namespace using "{namespace unknownNamespace=Some\Package\ViewHelpers}"
* you're trying to use a non-fluid xml namespace, in which case you can use "{namespace unknownNamespace}" to ignore this namespace for fluid rendering
```

## Actual output

```
<unknownNamespace:foo />
```

### PR DESCRIPTION
**Pull request by mneuhaus**
closes #8

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Commit message CGL (lowercase letter after prefix) - other than that, this looks good to me. If I'm not mistaken it is very much expected that *nothing whatsoever* inside CDATA gets processed so completely stripping it out seems like the right way.

**Comment by mneuhaus** [comment]
Commit message updated :)

**Comment by bwaidelich** [comment]
This doesn't solve the issue completely unfortunately..

```
some line
<![CDATA[{nonExistingNamespace:bar()}]]>
```

## Expected:

```
some line
{nonExistingNamespace:bar()}
```

## Actual:

```
Error: Unknown Namespace: nonExistingNamespace:bar() (0). Template code: 
</body>
</html>
```

**Comment by bwaidelich** [comment]
..it might work to add the ``m`` modifier to ``$SCAN_PATTERN_CDATA`` - but I wonder why this new issue occurred suddenly, maybe we should investigate..

**Comment by NamelessCoder** [comment]
> but I wonder why this new issue occurred suddenly, maybe we should investigate..

I don't think it did occur suddenly. It was silent until unregistered namespaces began throwing exception - and the decision to *not* do that lies quite a while back and has been discussed and undone since then ;)

**Comment by NamelessCoder** [comment]
Replaced by #27

**Pull request closed without merging**
